# Generated by Django 4.0.4 on 2022-06-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLogin', '0003_userblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
