# Generated by Django 4.0.4 on 2022-06-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLogin', '0006_alter_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupdate',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userupdate',
            name='link',
        ),
    ]
