# Generated by Django 4.0.4 on 2022-06-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogChat', '0002_chatperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatPerson',
        ),
    ]
